Makefile: fix clippy with CARGO_HACK
Running `make clippy CARGO_HACK=1` fails with:

    error: --no-default-features may not be used together with --each-feature

The `SVSM_ARGS_TEST` variable is only used to run tests. No need to use
it in clippy.

Fixes: a097c1dd ("xbuild: use packit as a library")
Suggested-by: Stefano Garzarella <sgarzare@redhat.com>
Signed-off-by: Luigi Leonardi <leonardi@redhat.com>